dailyfresh/dailyfresh/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include('df_user.urls')),
    url(r'^goods/', include('df_goods.urls')),
    url(r'^cart/', include('df_cart.urls')),
    url(r'^order/', include('df_order.urls')),
    url(r'^', include('df_goods.urls', namespace='goods')),

]

dailyfresh/df_cart/urls.py
from django.conf.urls import url
from .views import *


urlpatterns = [
    url(r'^$', cart),
    url(r'^add(\d+)_(\d+)/$', add),
    url(r'^edit(\d+)_(\d+)/$', edit),
    url(r'^delete(\d+)/$', delete),

]

dailyfresh/df_user/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^register/$', register),
    url(r'^register_handle/$', register_handle),
    url(r'^register_exist/', register_exist),
    url(r'^login/$', login),
    url(r'^login_handle/$', login_handle),
    url(r'^info/$', info),
    url(r'^site/$', site),
    url(r'^logout/$', logout),
    url(r'^user_center_order&(\d+)/$', user_center_order),
    url(r'^check_code/$', check_code)
]

dailyfresh/df_order/models.py
from django.db import models

# Create your models here.

class OrderInfo(models.Model):
    oid = models.CharField(max_length=20,primary_key=True)
    user = models.ForeignKey('df_user.UserInfo')
    odate = models.DateTimeField(auto_now=True)
    oIsPay = models.IntegerField(default=0)
    ototal = models.DecimalField(max_digits=6,decimal_places=2)
    oaddress = models.CharField(max_length=150,default='')
    zhifu = models.IntegerField(default=0)



class OrderDetailInfo(models.Model):
    goods = models.ForeignKey('df_goods.GoodsInfo')
    order = models.ForeignKey(OrderInfo)
    price = models.DecimalField(max_digits=5,decimal_places=2)
    count = models.IntegerField()

dailyfresh/df_user/models.py
# coding=utf-8
from django.db import models

# Create your models here.


class UserInfo(models.Model):
    uname = models.CharField(max_length=20)
    upwd = models.CharField(max_length=40)
    uemail = models.CharField(max_length=30, unique=True)
    ushou = models.CharField(max_length=20, default='')
    uaddress = models.CharField(max_length=100, default='')
    upostcode = models.CharField(max_length=6, default='')
    uphone = models.CharField(max_length=11, unique=True)
    # default,blank是python 层面的约束,不影响数据表结构

    def __str__(self):
        return self.uname

dailyfresh/df_user/views.py
import json
import hashlib
import random
import re
import urllib
import http.client

from django.core.paginator import Paginator
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from .models import *
from hashlib import sha1
from .islogin import *
from df_goods.models import *
from df_order.models import OrderInfo
from df_cart.models import *

# Create your views here.


def register(request):
    context = {'title': '用户注册'}
    return render(request, 'df_user/register.html', context)


# 处理注册
def register_handle(request):
    # 接收用户输入数据
    post = request.POST
    uname = post.get('user_name')
    upwd = post.get('pwd')
    uphone = post.get('user_phone')
    uemail = post.get('email')
    code = post.get("code")
    # 密码加密
    s1 = sha1()
    s1.update(upwd.encode('utf8'))  # 指定编码格式,否则会报错
    upwd_jm = s1.hexdigest()
    # 创建对象
    user = UserInfo()
    user.uname = uname
    user.uphone = uphone
    user.upwd = upwd_jm
    user.uemail = uemail
    if code == request.session.get("message_code", None):
        user.save()
        # 注册成功转到登录页面
        return redirect('/user/login/')
    return redirect('/user/register')


# 判断用户名或手机号或邮箱是否已经存在
def register_exist(request):
    dic = {}
    # 验证用户名是否已存在
    if 'uname' in request.GET:
        uname = request.GET['uname']
        # 判断用户名是否有特殊字符,防止sql注入
        L = re.findall(r'[\w-]+', uname)
        print(L)
        if L[0] != uname:
            dic['status'] = 2
        else:
            # count()返回查询的结果数,要么是0要么是1
            count = UserInfo.objects.filter(uname=uname).count()
            dic['status'] = count
        return HttpResponse(json.dumps(dic))
    # 验证手机号是否已存在,发送短信验证码
    elif 'uphone' in request.GET:
        uphone = request.GET['uphone']
        count = UserInfo.objects.filter(uphone=uphone).count()
        print(uphone)
        dic['status'] = count
        return HttpResponse(json.dumps(dic))

    elif 'uemail' in request.GET:
        uemail = request.GET['uemail']
        count = UserInfo.objects.filter(uemail=uemail).count()
        dic['status'] = count
        return HttpResponse(json.dumps(dic))


# 验证码
def check_code(request):
    host = "106.ihuyi.com"
    sms_send_uri = "/webservice/sms.php?method=Submit"
    # 用户名是登录ihuyi.com账号名（例如：cf_demo123）
    account = "C61395953"
    # 密码 查看密码请登录用户中心->验证码、通知短信->帐户及签名设置->APIKEY
    password = "56cf431c085a18ee77f19ad2b492324f"
    uphone = request.GET['uphone']
    # 定义一个字符串,存储生成的6位数验证码
    message_code = ''
    for i in range(6):
        i = random.randint(0, 9)
        message_code += str(i)

    # 拼接成发出的短信
    text = "您的验证码是：" + message_code + "。请不要把验证码泄露给其他人。"
    # 把请求参数编码
    params = urllib.parse.urlencode(
        {'account': account,
         'password': password,
         'content': text,
         'mobile': uphone,
         'format': 'json'})
    # 请求头
    headers = {
        "Content-type": "application/x-www-form-urlencoded", "Accept": "text/plain"}
    # 通过全局的host去连接服务器
    conn = http.client.HTTPConnection(host, port=80, timeout=30)
    # 向连接后的服务器发送post请求,路径sms_send_uri是全局变量,参数,请求头
    conn.request("POST", sms_send_uri, params, headers)
    # 得到服务器的响应
    response = conn.getresponse()
    # 获取响应的数据
    response_str = response.read()
    # 关闭连接
    conn.close()
    # 把验证码放进session中
    request.session['message_code'] = message_code
    print("哈哈哈")
    print(response_str.decode())
    print(eval(response_str.decode()))
    # 使用eval把字符串转为json数据返回
    return JsonResponse(eval(response_str.decode()))


# 登录页面
def login(request):
    uname = request.COOKIES.get('userlogin', '')
    context = {'title': '用户登录', 'error_pwd': 1, 'userlogin': uname}
    return render(request, 'df_user/login.html', context)


# 登录处理
def login_handle(request):
    # 接收数据
    userlogin = request.POST['userlogin']
    leng = len(userlogin)
    print(userlogin)
    upwd = request.POST['pwd']
    jizhu = request.POST.get('jizhu', 0)
    print(upwd)
    print(jizhu)
    # 创建加密对象
    s1 = sha1()
    s1.update(upwd.encode('utf8'))
    upwd = s1.hexdigest()

    if re.findall(r'^1\d{10}', userlogin):
        user = UserInfo.objects.filter(uphone=userlogin, upwd=upwd)
    elif re.findall(r'^\w+$', userlogin):
        user = UserInfo.objects.filter(uname=userlogin, upwd=upwd)
    else:
        user = UserInfo.objects.filter(uemail=userlogin, upwd=upwd)
    print("-----------------------")
    print('user', user)
    if not user:
        context = {'title': '用户登录', 'error_pwd': 0, 'userlogin': userlogin}
        return render(request, 'df_user/login.html', context)
    else:
        # 登录成功去往主页
        resp = HttpResponseRedirect('/')
        count = CartInfo.objects.filter(user_id=user[0].id).count()
        if jizhu != 0:
            resp.set_cookie('userlogin', userlogin)
        else:
            resp.set_cookie('userlogin', '', max_age=-1)
        request.session['user_id'] = user[0].id
        request.session['user_name'] = user[0].uname
        request.session['count'] = count
        return resp


# 登录用户中心
@islogin
def info(request):
    user_email = UserInfo.objects.get(id=request.session['user_id']).uemail

    # 最近浏览
    goods_ids = request.COOKIES.get('goods_ids', '')
    goods_id_list = goods_ids.split(',')
    goods_list = []
    if len(goods_ids):
        for goods_id in goods_id_list:
            goods_list.append(GoodsInfo.objects.get(id=int(goods_id)))

    context = {'title': '用户中心',
               'user_email': user_email,
               'user_name': request.session['user_name'],
               'page_name': 1,
               'info': 1,
               'goods_list': goods_list}
    return render(request, 'df_user/user_center_info.html', context)


# 订单
@islogin
def order(request):
    context = {'title': '用户中心', 'page_name': 1, 'order': 1}
    return render(request, 'df_user/user_center_order.html', context)


# 收货地址
@islogin
def site(request):
    user = UserInfo.objects.get(id=request.session['user_id'])
    if request.method == 'POST':
        post = request.POST
        user.ushou = post.get('ushou')
        user.uaddress = post.get('uaddress')
        user.uphone = post.get('uphone')
        user.upostcode = post.get('uyoubian')
        user.save()

    context = {'title': '用户中心', 'user': user, 'page_name': 1, 'site': 1}
    return render(request, 'df_user/user_center_site.html', context)


def logout(request):
    # 清除会话数据，在存储中删除会话的整条数据
    request.session.flush()
    return redirect('/')


@islogin
def user_center_order(request, pageid):
    """
    此页面向用户展示用户提交的订单,由购物车页面下单后转调过来，也可以从个人信息页面查看
    根据用户订单是否支付、下单顺序进行排序
    :param request:
    :param pageid:
    :return:
    """
    uid = request.session.get('user_id')
    # 订单信息,根据是否支付,下单顺序进行排序
    orderinfos = OrderInfo.objects.filter(
        user_id=uid).order_by('zhifu', '-oid')

    # 分页
    # 获取orderinfos list 以两个为一页的list
    paginator = Paginator(orderinfos, 2)
    # 获取上面集合的第pageid 个值
    orderlist = paginator.page(int(pageid))
    # 获取一共多少页
    plist = paginator.page_range
    # 3页分页显示
    qian1 = 0
    hou = 0
    hou2 = 0
    qian2 = 0
    dd = int(pageid)
    lenn = len(plist)
    if dd > 1:
        qian1 = dd - 1
    if dd >= 3:
        qian2 = dd - 2
    if dd < lenn:
        hou = dd + 1

    if dd+2 <= lenn:
        hou2 = dd + 2

    # 构造上下文
    context = {'page_name': 1, 'title': '全部订单', 'pageid': int(pageid),
               'order': 1, 'orderlist': orderlist, 'plist': plist,
               'pre': qian1, 'next': hou, 'pree': qian2, 'lenn': lenn, 'nextt': hou2}
    return render(request, 'df_user/user_center_order.html', context)

dailyfresh/templates/df_user/base.html
{% extends 'base.html' %}
{% block body %}
<div class="main_con clearfix">
  <div class="left_menu_con clearfix">
  <h3>用户中心</h3>
  <ul>
    <li><a href="/user/info"{% if info %} class="active"{% endif %}>· 个人信息</a></li>
    <li><a href="/user/user_center_order&1/"{% if order %} class="active"{% endif %}>· 全部订单</a></li>
    <li><a href="/user/site"{% if site %} class="active"{% endif %}>· 收货地址</a></li>
  </ul>
  </div>
  {% block right_content %}
  {% endblock right_content %}
</div>
{% endblock body %}

dailyfresh/templates/df_user/base_foot.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>{{ title }}-天天生鲜</title>
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/main.css">
	<script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
	<script src="/static/js/jquery-1.11.3.js" type="text/javascript"></script>
    {%block head%}{%endblock head%}
</head>

<body>
{% block body %}{% endblock body %}

	<div class="footer no-mp">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>

</body>
</html>

dailyfresh/templates/df_user/login.html
{% extends 'df_user/base_foot.html' %}
{% block head %}
    <script>
    $(function () {
        name_error=false
        pwd_error=false
        if($('.name_input').val().length!=0){
            name_error = true
        }
        if($('.pwd_error').val().length!=0){
            pwd_error = true
        }


        if({{ error_pwd }}== 0){
            $('.pwd_error').html('登录信息错误').show()
        }

        $('.name_input').blur(function(){
            check_name();
        });

        $('.pass_input').blur(function () {
            check_pwd();
        });

        //检查用户名或手机号或邮箱是否符合规则
        function check_name(){
            var name = $('.name_input').val();
            var re_name = /^\d*[a-zA-Z]+\d*$/;
            var re_phone = /^((13[0-9])|(14[5,7])|(15[0-3,5-9])|(17[0,3,5-8])|(18[0-9])|166|198|199|(147))\d{8}$/;
            var re_email = /^[a-z0-9][\w\.\-]*@[a-z0-9\-]+(\.[a-z]{2,5}){1,2}$/;
            if(!re_phone.test(name)&&!re_name.test(name)&&!re_email.test(name)){
                $('.user_error').html('输入格式有误').show();
                name_error=false;
            }else {
                $('.user_error').hide();
                name_error=true;
            }
        }

        //检查密码是否符合规则
        function check_pwd(){
            var pwd = $('.pass_input').val();
            if(pwd.length<6||pwd.length>18){
                $('.pwd_error').html('请输入6-18位的密码').show();
                pwd_error=false
            } else {
                $('.pwd_error').hide();
                pwd_error=true;
            }
        }


        //为表单绑定提交事件
        $("#form").submit(function(){
            check_name();
            check_pwd();
            console.log(pwd_error,name_error);
            if(pwd_error==false || name_error==false){
                return false;//此处阻止提交表单
            }
            return true;
        });

    })
    </script>
{% endblock head %}
{% block body %}
<body>
	<div class="login_top clearfix">
		<a href="index.html" class="login_logo"><img src="/static/images/logo02.png"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="/user/register/">立即注册</a>
				</div>
				<div class="form_input">
					<form id="form" action="/user/login_handle/" method="post">
                        {% csrf_token %}
						<input type="text" name="userlogin" class="name_input" value="{{ userlogin }}" placeholder="请输入用户名/手机号/邮箱">
						<div class="user_error">输入错误</div>
						<input type="password" name="pwd" class="pass_input" placeholder="请输入密码">
						<div class="pwd_error">输入错误</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="jizhu" value="1">
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input id="lo" type="submit" name="" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>
{% endblock body %}

dailyfresh/templates/df_user/register.html
{% extends 'df_user/base_foot.html' %}
{% load static from staticfiles %}
{% block head %}
<script type="text/javascript" src="{% static  'js/rg.js' %}"></script>

{% endblock head %}


{% block body %}
	<div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo"><img src="/static/images/logo02.png"></a>
			<div class="reg_slogan">足不出户  ·  新鲜每一天</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="/user/login/">登录</a>
			</div>
			<div class="reg_form clearfix">
				<form action="/user/register_handle/" id="reg_form" method="post">
                    {% csrf_token %}
                    <ul>
                        <li>
                            <label>用户名:</label>
                            <input type="text" name="user_name" id="user_name">
                            <span class="error_tip">提示信息</span>
                        </li>
                        <li>
                            <label>手机号:</label>
                            <input type="text" name="user_phone" id="user_phone">
                            <span class="error_tip">提示信息</span>
                        </li>
                        <li>
                            <label>密码:</label>
                            <input type="password" name="pwd" id="pwd">
                            <span class="error_tip">提示信息</span>
                        </li>
                        <li>
                            <label>确认密码:</label>
                            <input type="password" name="cpwd" id="cpwd">
                            <span class="error_tip">提示信息</span>
                        </li>
                        <li>
                            <label>邮箱:</label>
                            <input type="text" name="email" id="email">
                            <span class="error_tip">提示信息</span>
                        </li>
                        <li>
                            <label for="">验证码:</label>
                            <input type="text" name="code" placeholder="请输入手机验证码" style="width: 150px;" id="check_code">
                            &nbsp;&nbsp;
                            <input type="button" value=" 获取验证码" id="zphone" style="width: 120px;margin-left: 10px;cursor:pointer;">
                        </li>
                        <li class="agreement">
                            <input type="checkbox" name="allow" id="allow" checked="checked">
                            <label>同意”天天生鲜用户使用协议“</label>
                            <span class="error_tip2">提示信息</span>
                        </li>
                        <li class="reg_sub">
                            <input  type="submit" value="注 册" name="">
                        </li>
                    </ul>
				</form>
			</div>

		</div>

	</div>
{% endblock body %}

dailyfresh/templates/df_user/user_center_info.html
{%extends 'df_user/base.html'%}
{% block right_content %}
		<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
							<li><span>用户名：</span>{{user_name}}</li>
							<li><span>联系方式：</span>{{user_email}}</li>
							<li><span>联系地址：</span>北京市昌平区</li>			
						</ul>
				</div>
				
				<h3 class="common_title2">最近浏览</h3>
				<div class="has_view_list">
					<ul class="goods_type_list clearfix">

				{%for goods  in goods_list%}
				<li>
					<a href="/{{goods.id}}"><img src="/static/{{goods.gpic}}"></a>
					<h4><a href="detail.html">{{goods.gtitle}}</a></h4>
					<div class="operate">
						<span class="prize">￥{{goods.gprice}}</span>
						<span class="unit">{{goods.gprice}}/{{goods.gunit}}</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
				{%endfor%}
			        </ul>
		        </div>
		</div>


{% endblock right_content %}

dailyfresh/templates/df_user/user_center_order.html
{%extends 'df_user/base.html'%}
{% block right_content %}
<div class="right_content clearfix">
    <h3 class="common_title2">全部订单</h3>
    {% for orderinfo in orderlist %}
    <ul class="order_list_th w978 clearfix">
        <li class="col01">{{orderinfo.odate}}</li>
        <li class="col02">订单号：{{orderinfo.oid}}</li>
        {% if orderinfo.zhifu == 1 %}
        <li class="col02 stress">已支付</li>
        {% else %}
        <li class="col02 stress">未支付</li>
        {% endif %}
    </ul>
    <table class="order_list_table w980">
        <tbody>
        <tr>
            <td width="55%">
                {% for item in orderinfo.orderdetailinfo_set.all %}
                <ul class="order_goods_list clearfix">
                    <li class="col01"><img src="/static/{{item.goods.gpic}}"></li>
                    <li class="col02">{{item.goods.gtitle}}<em><span>{{item.price}}</span>元/{{item.goods.gunit}}</em>
                    </li>
                    <li class="col03">{{item.count}}个</li>
                    <li class="col04"></li>
                </ul>
                {% endfor %}
            </td>
            <td width="15%">{{orderinfo.ototal}}元</td>
            {% if orderinfo.zhifu == 1 %}
            <td width="15%">已付款</td>
            <td width="15%"><a href="#" class="oper_btn">查看物流</a></td>
            {% else %}
            <td width="15%">未付款</td>
            <td width="15%"><a href="/order/pay&{{orderinfo.oid}}/" class="oper_btn">去付款</a></td>
            {% endif %}
        </tr>
        </tbody>
    </table>
    {% endfor %}
    <div class="pagenation">
        {% if orderlist.has_previous %}
        <a href="/user/user_center_order&{{orderlist.previous_page_number}}/">
            上一页
        </a>
        {% endif %}
{#    分页 ： plist 一共多少页  pageid 当前页  orderlist paginator按照两个一页，分的，页的指向对象  #}
    {% if lenn < 4  %}
        {% if lenn == 1 %}
            <a href="/user/user_center_order&{{pageid}}/" class="active">{{pageid}}</a>
        {% elif lenn == 2 %}
            {% if pageid == 1 %}
            <a href="/user/user_center_order&{{pageid}}/" class="active">{{pageid}}</a>
            <a href="/user/user_center_order&{{next}}/" >{{next}}</a>
            {% else %}
            <a href="/user/user_center_order&{{pre}}/" >{{pre}}</a>
            <a href="/user/user_center_order&{{pageid}}/" class="active">{{pageid}}</a>
            {% endif %}
        {% elif lenn == 3%}

            {% if pageid == 1 %}
            <a href="/user/user_center_order&{{pageid}}/" class="active">{{pageid}}</a>
            <a href="/user/user_center_order&{{next}}/" >{{next}}</a>
            <a href="/user/user_center_order&{{nextt}}/" >{{nextt}}</a>
            {% elif pageid == 2 %}
            <a href="/user/user_center_order&{{pre}}/" >{{pre}}</a>
            <a href="/user/user_center_order&{{pageid}}/" class="active">{{pageid}}</a>
            <a href="/user/user_center_order&{{next}}/" >{{next}}</a>
            {% else %}
            <a href="/user/user_center_order&{{pree}}/" >{{pree}}</a>
            <a href="/user/user_center_order&{{pre}}/" >{{pre}}</a>
            <a href="/user/user_center_order&{{pageid}}/" class="active">{{pageid}}</a>
            {% endif %}
        {% endif %}
    {% elif pageid < lenn %}
        {% if orderlist.has_previous  %}
        <a href="/user/user_center_order&{{pre}}/" >{{pre}}</a>
        <a href="/user/user_center_order&{{pageid}}/" class="active">{{pageid}}</a>
        <a href="/user/user_center_order&{{next}}/" >{{next}}</a>
        {% else %}
        <a href="/user/user_center_order&{{pageid}}/" class="active">{{pageid}}</a>
        <a href="/user/user_center_order&{{next}}/" >{{next}}</a>
        <a href="/user/user_center_order&{{nextt}}/" >{{nextt}}</a>
        {% endif %}
    {% else %}
        <a href="/user/user_center_order&{{pree}}/" >{{pree}}</a>
        <a href="/user/user_center_order&{{pre}}/" >{{pre}}</a>
        <a href="/user/user_center_order&{{pageid}}/" class="active">{{pageid}}</a>
    {% endif %}


        {% if orderlist.has_next %}
        <a href="/user/user_center_order&{{orderlist.next_page_number}}/">下一页></a>
        {% endif %}
    </div>
</div>


{%endblock right_content %}

dailyfresh/templates/df_user/user_center_site.html
{%extends 'df_user/base.html'%}
{%block right_content %}
		<div class="right_content clearfix">
				<h3 class="common_title2">收货地址</h3>
				<div class="site_con">
					<dl>
						<dt>当前地址：</dt>
						<dd>{{user.uaddress}} ({{user.ushou}} 收) 电话：{{user.uphone}} 邮编：{{user.uyoubian}} </dd>
					</dl>					
				</div>
				<h3 class="common_title2">编辑地址</h3>
				<div class="site_con">
					<form action="/user/site/" method="post">
						{%csrf_token%}
						<div class="form_group">
							<label>收件人：</label>
							<input type="text" name="ushou" value="{{user.ushou}}">
						</div>
						<div class="form_group form_group2">
							<label>详细地址：</label>
							<textarea class="site_area" name="uaddress">{{user.uaddress}}</textarea>
						</div>
						<div class="form_group">
							<label>邮编：</label>
							<input type="text" name="uyoubian" value="{{user.uyoubian}}">
						</div>
						<div class="form_group">
							<label>手机：</label>
							<input type="text" name="uphone" value="{{user.uphone}}">
						</div>

						<input type="submit" name="" value="提交" class="info_submit">
					</form>
				</div>
		</div>
	</div>

{%endblock right_content %}